classbasedpro/classbasedpro/urls.py
from django.conf.urls import url
from django.contrib import admin
from genericviews import views
from django.conf.urls import include



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^genericviews/', include('genericviews.urls')),
]

classbasedpro/genericviews/urls.py
from django.conf.urls import url
from genericviews import views

app_name ='genericviews'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name="detail"),
    url(r'^makeentry$',views.makeentry,name='makeentry')
]

classbasedpro/genericviews/models.py
from django.db import models
class Person(models.Model):
    name=models.CharField(max_length=100)
    desc = models.CharField(max_length=400)
    def __str__(self):
        return self.name

classbasedpro/genericviews/forms.py
from django import forms
class PersonForm(forms.Form):
    name=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'your name',
            }
        )
    )
    desc = forms.CharField(help_text="write a brief about person",
        widget=forms.Textarea(
            attrs={
                    'class':'form-control',
                    'placeholder':'enter description',
            }
        )
    )

classbasedpro/genericviews/views.py
from django.shortcuts import render
from django.views import generic
from .forms import PersonForm
from .models import Person
from django.shortcuts import get_object_or_404

def makeentry(request):
    if request.method=="POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            name= request.POST.get('name','')
            desc = request.POST.get('desc','')
        data=Person(name = name,desc= desc)
        data.save()
        form = PersonForm()
        return render(request,'genericviews/makeentry.html',{'form':form})

    else:
        form = PersonForm()
        return render(request,'genericviews/makeentry.html',{'form':form})

class IndexView(generic.ListView):
    context_object_name = 'list'
    template_name = 'genericviews/index.html'
    def get_queryset(self):
        return Person.objects.all()

class DetailView(generic.DetailView):
    model = Person
    template_name = 'genericviews/detail.html'

    def get_object(self,*args,**kwargs):
        a = self.kwargs.get('pk')
        print(a)
        print('print is working')
        return get_object_or_404(Person,pk=self.kwargs.get('PK'))

classbasedpro/templates/genericviews/detail.html
<h1>{{ person.name }}</h1>
<h3>{{ person.desc }}</h3>

classbasedpro/templates/genericviews/index.html
{% if list %}
  <h1>Person Details! </h1>
  <ul>
     {% for person in list %}
      <li>
  <a href="{% url 'genericviews:detail' person.id %}">{{ person.name }}</a>
      </li>
     {% endfor %}
  </ul>
{% else %}
<h3> No Person found.</h3>
{% endif %}

classbasedpro/templates/genericviews/makeentry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Entry</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    body{
        background-color: paleturquoise;
        }
    .container{
        background-color: antiquewhite;
        border-radius: 10px;
        margin-top: 40px;
    }
    form{
        border: 5px;
        border-color: red;
    }
</style>

</head>
<body>
<div class="container">
    <h1 class="text-center">please make entries here</h1>
    <div class="row">
        <div class="col-md-5">
            <form action="{% url 'genericviews:makeentry' %}" method="post">
                {% csrf_token %}
                {{ form }}<br>
                <center><input type="submit" value="submit"></center>
            </form>
        </div>
    </div>
</div>
</body>
</html>